from fastapi import APIRouter, HTTPException, Header, Depends
from pydantic import BaseModel
from google.oauth2 import id_token
from google.auth.transport import requests as google_requests
from db import tinydb_schema as db
from config import get_settings


settings = get_settings()
router = APIRouter()


class GCSWebhookPayload(BaseModel):
    gcs_path: str
    file_size_bytes: int


def verify_gcp_oidc_token(authorization: str = Header(...)):
    """Verifies the OIDC token sent by the Google Cloud Function."""
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid Authorization header")

    token = authorization.split(" ")[1]
    expected_audience = f"{settings.base_url}/api/webhooks/gcs"

    try:
        request = google_requests.Request()
        id_info = id_token.verify_oauth2_token(token, request, expected_audience)

        if id_info.get("email") != settings.gcs_service_account_email:
            raise ValueError("Token generated by unknown service account.")

        return id_info
    except ValueError as e:
        raise HTTPException(status_code=401, detail=f"Unauthorized Webhook Call: {str(e)}")


@router.post("/gcs")
def gcs_upload_complete(
        payload: GCSWebhookPayload,
        token_info: dict = Depends(verify_gcp_oidc_token)
):
    img = db.get_image_by_gcs_path(payload.gcs_path)
    if not img:
        raise HTTPException(status_code=404, detail="Unknown image")

    try:
        db.confirm_image_upload(img["image_id"], payload.file_size_bytes)
        return {"status": "success", "message": "Image marked as ready"}
    except db.ResourceNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))